# Generated by Django 5.1.3 on 2024-12-12 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_userprofile_address_userprofile_semester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='complications_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgery',
            name='histology',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surgery',
            name='histology_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgery',
            name='main_surgeon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surgery',
            name='notes1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgery',
            name='notes2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='complications',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='name_of_surgery',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='type_of_surgery',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('travel_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accommodation_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scientific',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types_works', models.CharField(blank=True, max_length=255, null=True)),
                ('international', models.BooleanField(default=False)),
                ('national', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('co_author_names', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
