# Generated by Django 5.1.3 on 2024-12-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='field_of_surgery',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='name_of_surgery',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='type_of_surgery',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
