# Generated by Django 5.1.3 on 2024-12-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_percantagesurgery'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='visible_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
