# Generated by Django 5.1.3 on 2024-12-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_notification_visible_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_sound_played',
            field=models.BooleanField(default=False),
        ),
    ]
