# Generated by Django 5.1.3 on 2024-12-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='free_trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
