# Generated by Django 5.1.3 on 2025-07-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_privacypolicy_termscondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
