# Generated by Django 5.1.3 on 2025-08-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_notificationtext_onetimenotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimenotification',
            name='notification_text',
        ),
        migrations.RemoveField(
            model_name='onetimenotification',
            name='user',
        ),
        migrations.AddField(
            model_name='budget',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='NotificationText',
        ),
        migrations.DeleteModel(
            name='OneTimeNotification',
        ),
    ]
